services:
  - type: web
    name: airaa-backend
    env: python
    rootDir: ai-agent
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 180
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DUNE_API_KEY
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: COINMARKETCAP_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false

